version: '3'

services:
    db:
        image: docker.pkg.github.com/m3xan1k/bandmate/db:latest
        container_name: 'bandmate_db'
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
    app:
        image: docker.pkg.github.com/m3xan1k/bandmate/app:latest
        container_name: 'bandmate_app'
        build: ./app
        command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/src/static/
        expose:
            - 8000
        env_file:
            - ./.env
        depends_on:
            - db
    nginx:
        image: docker.pkg.github.com/m3xan1k/bandmate/nginx:latest
        container_name: 'bandmate_nginx'
        build: ./nginx
        volumes:
            - static_volume:/src/static/
        ports:
            - 80:80
        depends_on:
            - app

volumes:
    postgres_data:
    static_volume:
