# Generated by Django 3.0.5 on 2020-04-27 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('BAND_IS_LOOKING', 'Band is looking for mate'), ('MUSICIAN_IS_LOOKING', 'Musician is looking for mates'), ('LOOKING_FOR_WORK', 'Looking for work'), ('WORK_IS_LOOKING', 'Work is looking')], default='BAND_IS_LOOKING', max_length=50),
        ),
    ]
