# Generated by Django 3.0.5 on 2020-04-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200427_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
