# Generated by Django 3.0.5 on 2020-04-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200427_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
