# Generated by Django 3.0.5 on 2020-04-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='instruments',
            field=models.ManyToManyField(related_name='musicians', to='bands.Instrument'),
        ),
    ]
