name: Docker image CI

on: [push, pull_request]

jobs:
    build:
        name: Build Docker Images
        runs-on: ubuntu-latest
        steps:
          - name: Checkout master
            uses: actions/checkout@v1
          - name: Setup .env file
            run: |
                DEBUG: ${{ secrets.DEBUG }} >> .env
                DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }} >> .env
                POSTGRES_USER: ${{ secrets.POSTGRES_USER }} >> .env
                POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} >> .env
                POSTGRES_DB: ${{ secrets.POSTGRES_DB }} >> .env
                SQL_ENGINE: ${{ secrets.SQL_ENGINE }} >> .env
                POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }} >> .env
                POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }} >> .env
                DATABASE: ${{ secrets.DATABASE }} >> .env
                EMAIL_HOST: ${{ secrets.EMAIL_HOST }} >> .env
                EMAIL_PORT: ${{ secrets.EMAIL_PORT }} >> .env
                EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }} >> .env
                EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }} >> .env
                DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }} >> .env
                SECRET_KEY: ${{ secrets.SECRET_KEY }} >> .env
          - name: Build docker-compose stack
            run: docker-compose up -d
          - name: Check running containers
            run: docker ps
          - name: Run tests
            run: docker exec bandmate_app python manage.py test
