name: Docker Image CI

on: [push]

jobs:
    build:
        name: Build Docker Images
        runs-on: ubuntu-latest
        env:
          DEBUG: ${{ secrets.DEBUG }}
          DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          SQL_ENGINE: ${{ secrets.SQL_ENGINE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          DATABASE: ${{ secrets.DATABASE }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        steps:
          - name: Checkout master
            uses: actions/checkout@v1
          - name: Create env
            run: |
              echo DEBUG=$DEBUG >> .env
              echo DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS >> .env
              echo POSTGRES_USER=$POSTGRES_USER >> .env
              echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
              echo POSTGRES_DB=$POSTGRES_DB >> .env
              echo SQL_ENGINE=$SQL_ENGINE >> .env
              echo POSTGRES_HOST=$POSTGRES_HOST >> .env
              echo POSTGRES_PORT=$POSTGRES_PORT >> .env
              echo DATABASE=$DATABASE >> .env
              echo EMAIL_HOST=$EMAIL_HOST >> .env
              echo EMAIL_PORT=$EMAIL_PORT >> .env
              echo EMAIL_HOST_USER=$EMAIL_HOST_USER >> .env
              echo EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD >> .env
              echo DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL >> .env
              echo SECRET_KEY=$SECRET_KEY >> .env 
          - name: Build docker-compose stack
            run: docker-compose up -d
          - name: Check running containers
            run: docker ps
          - name: Make migrations
            run: docker exec bandmate_app python manage.py makemigrations bands
          - name: Migrate
            run: docker exec bandmate_app python manage.py migrate
          - name: Run tests
            run: docker exec bandmate_app python manage.py test
